version: '2.1'

services:
  grafana-01:
    image: grafana/grafana
    container_name: grafana-01
    ports:
      - 3000:3000
    networks:
      - arch-network
  
  prometheus-01:
    image: prom/prometheus
    container_name: prometheus-01
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - arch-network

  
  mai-db-node-ex01:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: mai-db-node-ex01
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mariadb --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - db-node-ex01-data:/var/lib/mysql

  my_service:
    build:
      context: my_service
      dockerfile: Dockerfile
    container_name: my_service
    environment:
      - DB_HOST=mai-db-node-ex01
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8080:8080
      - 9100:9100
    networks:
      - arch-network
    depends_on:
      mai-db-node-ex01:
        condition: service_healthy  

volumes:
  db-node-ex01-data:

networks:
  arch-network:
    driver: "bridge"
    external: false